name: mentor_guardian
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Add the following section for latest transitive dependencies
dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  meta: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - images/blog1.png
    - images/blog2.png
    - images/blog3.jpg
    - images/bell_icon.png
    - images/profile_icon.png
    - images/explore_icon.png
    - images/learning_icon.png
    - images/home_icon.png
    - images/home1.png
    - images/no_notification.png
    - images/profile_pic.png
    - images/challenges.png
    - images/community.png
    - images/live_events.png
    - images/telecoaching.png
    - images/productivity.png
    - images/organization.png
    - images/mindfulness.png
    - images/managing_emotions.png
    - images/LoginPage_PNG.png
